version: '3'
services:
  react-app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./:/app
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./build:/usr/share/nginx/html:ro
    depends_on:
      - react-app
